

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    # volumes:
    #   - ../frontend/dist:/app/frontend/dist # Mount the frontend/dist directory
    # environment:
    #   - NODE_ENV=docker
    command: npm run dev