# version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: transcendence-backend
    environment:
      - APP_URL=https://10.12.3.3:8443
      - NODE_ENV=production
      - JWT_SECRET=hbj2io4@@#!v7946h3&^*2cn9!@09*@B627B^*N39&^847,1
    ports:
      - "8443:8443"
    volumes:
      - ./backend/data_controller/data:/workspace/backend/data_controller/data
      - ./backend/https_keys:/workspace/backend/https_keys
      - ./uploads:/workspace/uploads
    command: ["npm", "run", "dev"]