# version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      args:
        - APP_URL=${APP_URL}
        - VITE_URL=${VITE_URL}
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    container_name: transcendence-backend
    env_file:
      - .env
    environment:
      - APP_URL=${APP_URL}
      - VITE_URL=${VITE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8443
    ports:
      - "8443:8443"
    volumes:
      - ./backend/data_controller/data:/workspace/backend/data_controller/data
      - ./uploads:/workspace/uploads
    command: ["npm", "run", "dev"]
    networks:
      - transcendence-network

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        - VITE_URL=${VITE_URL}
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    container_name: transcendence-frontend
    env_file:
      - .env
    environment:
      - VITE_URL=${VITE_URL}
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - transcendence-network

networks:
  transcendence-network:
    driver: bridge
